//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Apigo_TechnicalExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string patientNo { get; set; }
        [Required(ErrorMessage = "Field required.")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Field required. \"N/A\" if none.")]
        public string middleName { get; set; }
        [Required(ErrorMessage = "Field required.")]
        public string lastName { get; set; }
        public string suffixName { get; set; }
        [Required(ErrorMessage = "Field required.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime birthDate { get; set; }
        [Required(ErrorMessage = "Field required.")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Field required.")]
        public string initialDiagnosis { get; set; }
    }
}
